# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build SimpleMongoMigrations --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build     
    - name: Pack
      run: dotnet pack SimpleMongoMigrations/SimpleMongoMigrations.csproj --configuration Release
    - name: Publish
      run: dotnet nuget push SimpleMongoMigrations/bin/Release/*.nupkg -k ${{ secrets.NUGET_APIKEY }} -s https://api.nuget.org/v3/index.json